namespace llvc
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Windows.Foundation.IAsyncAction OpenProjectPath(String path);
    }
}
