// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UartMonitor
{
    internal sealed partial class Vsix
    {
        public const string Id = "UartMonitor.5c5cab1a-0063-4837-949a-13f581ef750e";
        public const string Name = "UartMonitor";
        public const string Description = @"UART monitor for embedded debug logs with ANSI-aware text rendering, HEX view, line timestamps, and synchronized selection";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "YePhIcK";
        public const string Tags = "UART, serial, monitor, log, debug, logging, embedded";
        public const bool IsPreview = false;
    }
}
